Repository nextcloud/ldap_write_support, pull requests merged in 2022-09, with the labels that each got.

#503 Use LDAP passwd exop to set password of new users
  lib/LDAPUserManager.php
  lib/Service/Configuration.php
Labels: bug, 3. to review, php

#509 Starting PHP 8.1 the LDAP connection is an object
  lib/LDAPConnect.php
  lib/LDAPUserManager.php
Labels: bug, 3. to review

#504 Modernize javascript code
  .eslintrc.js
  .github/workflows/nodejs.yml
  .nextcloudignore
  .stylelintrc.js
  babel.config.js
  css/admin-settings.scss
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/main-settings.js
  src/mixins/i10n.js
  src/webpack.common.js
  src/webpack.dev.js
  src/webpack.prod.js
  templates/settings-admin.php
  webpack.js
Labels: enhancement, 3. to review, javascript
