Repository nextcloud/ldap_write_support, pull requests merged in 2024-01, with the labels that each got.

#630 [master] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#628 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#623 [stable26] Update nextcloud/ocp dependency
  composer.json
  composer.lock
Labels: dependencies, 3. to review

#626 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#625 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#636 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#637 [stable26] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#640 update dependencies to fix nextcloud/ocp CI job
  composer.json
  composer.lock
  lib/AppInfo/Application.php
Labels: 3. to review

#646 Update npm and node engines versions
  package.json
Labels: dependencies

#642 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#641 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#645 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#644 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#643 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#647 Switched to node.yml workflow from nextcloud/.github
  .github/workflows/node.yml
  .github/workflows/nodejs.yml
Labels: 3. to review

#649 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#650 [master] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#654 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
