Repository nextcloud/ldap_write_support, pull requests merged in 2024-08, with the labels that each got.

#790 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#794 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#795 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#802 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#760 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#762 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#761 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#787 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#803 chore: Update package-lock file (NPM audit)
  package-lock.json
  package.json
Labels: 3. to review

#804 [stable30] fix: Adjust package-lock (NPM audit)
  package-lock.json
  package.json
Labels: 3. to review

#806 Release for 30
  release.sh
Labels: 4. to release

#807 chore: Improve release script a bit
  release.sh
Labels: 4. to release

#812 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#813 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#814 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#811 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#808 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#815 fix(dependabot): Add composer to updates
  .github/dependabot.yml
Labels: 3. to review
