Repository nextcloud/ldap_write_support, pull requests merged in 2024-03, with the labels that each got.

#672 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#673 feat: Migrate to build the frontend using vite
  .eslintrc.js
  .eslintrc.json
  .gitignore
  .stylelintrc.cjs
  babel.config.js
  lib/Settings/Admin.php
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/main-settings.js
  templates/settings-admin.php
  vite.config.js
  webpack.js
Labels: enhancement, 3. to review

#674 Release for 29
  release.sh
Labels: 4. to release

#677 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#683 [stable28] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#676 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#686 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#678 [stable27] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#675 chore: update workflows from templates
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/psalm.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
Labels: dependencies, 3. to review, automated

#688 Fix Drone stable26
  .drone.yml
Labels: 3. to review, technical debt

#685 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#684 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#687 Fix Drone stable27
  .drone.yml
Labels: 3. to review, technical debt

#679 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#694 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#693 feat: Enable translation of ldap_write_support app
  .l10nignore
  .tx/config
  l10n/.gitkeep
Labels: enhancement, 3. to review

#697 [stable28] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#696 [stable27] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#695 [stable26] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#704 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
