Repository nextcloud/ldap_write_support, pull requests merged in 2025-02, with the labels that each got.

#914 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#915 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#918 fix: Fix typo in script name
  lib/Settings/Admin.php
  package-lock.json
  package.json
Labels: 3. to review

#921 [stable29] fix: Fix typo in script name
  lib/Settings/Admin.php
  package-lock.json
  package.json
Labels: 3. to review

#923 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#925 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#920 [stable30] fix: Fix typo in script name
  lib/Settings/Admin.php
  package-lock.json
  package.json
Labels: 3. to review

#931 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#932 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#924 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#933 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#935 chore: release v1.11.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
  release.sh
Labels: 4. to release

#934 chore: release 1.12.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
  release.sh
Labels: 4. to release

#916 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#887 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#886 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#936 chore: release v1.13.0 for Nextcloud 31
  CHANGELOG.md
  release.sh
Labels: 4. to release

#939 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#940 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#941 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#942 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
