Repository nextcloud/ldap_write_support, pull requests merged in 2025-06, with the labels that each got.

#1021 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#1023 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#1025 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#992 [stable29] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#991 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#1035 chore: Run install and not update in vendor-bin on post-update
  composer.json
Labels: 4. to release

#1033 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1029 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#1030 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#990 [stable31] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
