Repository nextcloud/ldap_write_support, pull requests merged in 2025-03, with the labels that each got.

#944 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#945 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#948 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#949 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#950 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#951 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#954 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#960 chore: Update CI workflows from upstream
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: 3. to review

#957 [stable30] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#958 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#961 Update ci workflows for stable31
  .github/workflows/appstore-build-publish.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/node.yml
  .github/workflows/npm-audit-fix.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/pr-feedback.yml
  .github/workflows/psalm.yml
  .github/workflows/reuse.yml
  .github/workflows/update-nextcloud-ocp-approve-merge.yml
  .github/workflows/update-nextcloud-ocp.yml
  psalm.xml
Labels: backport-request, 3. to review

#964 [stable29] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#965 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#966 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#968 [stable31] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#969 [main] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review

#970 [stable30] Update nextcloud/ocp dependency
  composer.lock
Labels: dependencies, 3. to review
